server:
  session:
    timeout: 21600

spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://localhost:9001/project-db
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.HSQLDialect
